name: Security PR handler

on: 
  pull_request:
    types: [ synchronize, labeled, unlabeled, opened, reopened ]

jobs:
  Check-PR-Forbidden-Tags:
    if: ${{ github.event.label.name == 'DON%25T MERGE' || github.event.label.name == 'Don%25t squash' }}
    runs-on: ubuntu-latest
    steps:
      - name: Forbidden tags detected
        run: echo "Don't merge / Don't squash tags detected. Failing to prevent merge"
      - name: Create failure
        run: exit 1
