name: Security PR handler

on: 
  pull_request:
    types: [ synchronize, labeled, unlabeled, opened, reopened ]

jobs:
  Check-PR-Forbidden-Tags:
    runs-on: ubuntu-latest
    steps:
      - name: Forbidden tags detection
        if: github.event.label.name == 'DON T MERGE' || github.event.label.name == 'Don t squash'
        run: | 
          echo "Don't merge / Don't squash tags detected. Failing to prevent merge"
          exit 1
